version: '3'

volumes:
 librenms-mysql:
 librenms-mysql-conf:
 librenms-server:
 librenms-server-opt:
 librenms-server-cron:
 librenms-server-nginx:

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    container_name: librenms-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
     - MYSQL_USER=librenms
     - MYSQL_PASSWORD=librenms
     - MYSQL_DATABASE=librenms
     - MYSQL_ROOT_PASSWORD=librenms
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
    cap_add:
     - SYS_NICE
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - librenms-mysql:/var/lib/mysql
     - librenms-mysql-conf:/etc/mysql

  server:
    image: librenms-w8
    restart: unless-stopped
    container_name: librenms-server
    environment:
     - TZ=America/Sao_Paulo
     - DB_HOST=db
     - DB_NAME=librenms
     - DB_USER=librenms
     - DB_PASSWORD=librenms
     - BILLING_CALCULATE_ENABLE=true
     - POLL_BILLING_ENABLE=true
    volumes:
     - librenms-server:/data
     - librenms-server-opt:/opt
     - librenms-server-cron:/etc/cron.d
     - librenms-server-nginx:/etc/nginx
    links:
     - db
    ports:
     - 8000:8000

  redis:
    image: redis:5.0-alpine
    container_name: librenms-redis
    command: redis-server --requirepass librenms
    environment:
     - TZ=America/Sao_Paulo
    restart: unless-stopped

  dispatcher:
    image: librenms-w8
    restart: unless-stopped
    container_name: librenms-dispatcher
    environment:
     - TZ=America/Sao_Paulo
     - DB_HOST=db
     - DB_NAME=librenms
     - DB_USER=librenms
     - DB_PASSWORD=librenms
     - SIDECAR_DISPATCHER=1
     - DISPATCHER_NODE_ID=1
     - REDIS_HOST=redis
     - REDIS_PASSWORD=librenms
    volumes:
     - librenms-server:/data
    links:
     - redis
